//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.17 at 12:17:01 PM EDT 
//


package org.spurlin.jqtest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.spurlin.jqtest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Total_QNAME = new QName("http://jqtest.spurlin.org/Rate", "total");
    private final static QName _Number_QNAME = new QName("http://jqtest.spurlin.org/Rate", "number");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.spurlin.jqtest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ratetest }
     * 
     */
    public Ratetest createRatetest() {
        return new Ratetest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jqtest.spurlin.org/Rate", name = "total")
    public JAXBElement<Double> createTotal(Double value) {
        return new JAXBElement<Double>(_Total_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jqtest.spurlin.org/Rate", name = "number")
    public JAXBElement<Integer> createNumber(Integer value) {
        return new JAXBElement<Integer>(_Number_QNAME, Integer.class, null, value);
    }

}
